### ISSUE TITLE
Dialogue and Pause Menu:

### ISSUE THREAD

**Issue by jreeee** [finnmito/steves-job#121]
Disable the Pause menu when in Dialogue, also the pause menu should draw _over_ Hints and not vice versa

**Comment by jreeee** [comment]
![entinue](https://user-images.githubusercontent.com/64651827/124452117-61236d80-dd86-11eb-8894-b627df5e09e0.png)

**Comment by jakobbbb** [comment]
In theory hints should be hidden:
https://github.com/finnmito/steves-job/blame/54ed505c776e884b3179a75e8489500246f1459e/Assets/Menu/PauseMenu/PauseMenu.cs#L46

But yeah, the escape menu needs to be in front of all other UI
