### ISSUE TITLE
Fix Horror Mall

### ISSUE THREAD

**Issue by Mielein** [finnmito/steves-job#53]
Fred's shirt is off since the start. 
Can't talk to Jimmy.
Cute Portal is missing.

**Comment by jreeee** [comment]
i can't even run the scene lol "NullReferenceException: Object reference not set to an instance of an object
FredNipples.Update () (at Assets/NPC/fred/FredNipples.cs:16)"

**Comment by jakobbbb** [comment]
A `GameManager` is required for everything to fully function.  We'll either need to add one to the scene or always start from the Menu, where one is created.
