### ISSUE TITLE
More Portals for easyer navigation throgh worlds

### ISSUE THREAD

**Issue by Fionn-the-goose** [finnmito/steves-job#64]
I think it would be good to have in each corner of the mal in cute and horror 1 portal and in void each 2﻿

**Comment by jakobbbb** [comment]
Here's what the portals look like in-game:

https://user-images.githubusercontent.com/26824491/123556803-aeec1480-d78d-11eb-848a-139cb8ae5342.mp4

Seems like for the initial mall layout we didn't account for the portals, so they're just kinda crammed in there for now.
I think we might need to do some adjustments to the layout to create some more space for the portals, or do you have a better idea for what to do?
