### ISSUE TITLE
Inventor Item use for Objkts on steve himself

### ISSUE THREAD

**Issue by Fionn-the-goose** [finnmito/steves-job#81]
I Think it would be nice to have some Interactions for steve with his items himself, for example, if he chose his mop he could hug it
or if he use some liquid he could drink it with an animation as an effect﻿

**Comment by jakobbbb** [comment]
Also I really want Steve to be able to drink the period blood cocktail so we can implement `SteveController.Vomit()`.

**Comment by jakobbbb** [comment]
Note:  The `E` hint should be shown whenever Steve can use an item on himself.  See #103 and it's PR for further info on how that's done :3

**Comment by jakobbbb** [comment]
"Super duper Idee," aber keine Zeit :-(
